
exports.parseGBF = function parseGBF(gbf) {

    gbf = gbf.split('\n');

    for(var origin = 0; origin < gbf.length; ++ origin)
        if(gbf[origin].indexOf('ORIGIN') === 0)
            break;

    var record = {

        /* Collapse everything after the origin (the sequence) into a single
         * string, removing line numbers and spaces.
         */
        sequence: gbf.slice(origin + 1).map(function(line) {

            return line.trim().split(' ').slice(1).join('');

        }).join('')

    };

    /* Parse everything before the ORIGIN (the annotations) with parseFlatFile
     */
    parseFlatFile(gbf.slice(0, origin)).forEach(function(field) {

        switch(field.name)
        {
        case 'LOCUS':

            /* LOCUS       SCU49845                5028 bp    DNA     PLN 23-MAR-2010 */
            var locus = field.value[0].match(/([^\s]+) +(\d+) bp +([A-Z]+) +([A-Z]+) +(\d\d-[A-Z]{3}-\d{4})/);

            if(locus !== null) {

                record.locusName = locus[1];
                record.sequenceLength = locus[2];
                record.moleculeType = locus[3];
                record.division = locus[4];
                record.modified = locus[5];
            }

            /* LOCUS       SCU49845                5028 bp    DNA     linear   PLN 23-MAR-2010 */
            locus = field.value[0].match(/([^\s]+) +(\d+) bp +([A-Z]+) +([a-z]+) +([A-Z]+) +(\d\d-[A-Z]{3}-\d{4})/);

            if(locus !== null) {

                record.locusName = locus[1];
                record.sequenceLength = locus[2];
                record.moleculeType = locus[3];
                record.moleculeTypeDisp = locus[4];
                record.division = locus[5];
                record.modified = locus[6];
            }

            /* LOCUS       Ga0070195_11      1491782 bp      DNA linear      29-MAR-2016 */
            locus = field.value[0].match(/([^\s]+) +(\d+) bp +([A-Z]+) +([a-z]+) +(\d\d-[A-Z]{3}-\d{4})/);

            if(locus !== null) {

                record.locusName = locus[1];
                record.sequenceLength = locus[2];
                record.moleculeType = locus[3];
                record.moleculeTypeDisp = locus[4];
                record.modified = locus[5];
            }

            break;

        case 'DEFINITION':

            record.definition = field.value.join(' ');
            break;

        case 'ACCESSION':

            record.accession = field.value.join(' ');
            break;

        case 'VERSION':

            record.version = field.value.join(' ');
            break;

        case 'KEYWORDS':

            if(field.value == '.')
                break;

            /* TODO */

            break;

        case 'SOURCE':

            record.source = {
                name: field.value.join(' ')
            };

            field.children.forEach(function(subfield) {

                if(subfield.name == 'ORGANISM') {

                    record.source.organism = {

                        name: subfield.value[0],

                        lineage: subfield.value.slice(1).join(' ').split('; ').map(function(s) {

                            s = s.trim();

                            return s[s.length - 1] == '.' ? s.slice(0, s.length - 1) : s;
                        })
                    };
                }
            });

            break;

        case 'REFERENCE':

            if(record.references === undefined)
                record.references = [];

            var bases = field.value[0].match(/^([0-9]+) +\(bases ([0-9]+) to ([0-9]+)\)$/);

            var reference = bases !== null ? {

                number: parseInt(bases[1]),
                start: parseInt(bases[2]),
                end: parseInt(bases[3])

            } : {};

            field.children.forEach(function(subfield) {
                switch(subfield.name)
                {
                case 'AUTHORS':
                    reference.authors = subfield.value.join(' ');
                    break;

                case 'TITLE':
                    reference.title = subfield.value.join(' ');
                    break;

                case 'JOURNAL':
                    reference.journal = subfield.value.join(' ');
                    break;

                case 'PUBMED':
                    reference.pubmed = subfield.value.join(' ');
                    break;
                };
            });

            record.references.push(reference);

            break;

       case 'FEATURES':

            record.features = [];

            field.children.forEach(function(feature) {

                var location = ''

                for(var i = 0; i < feature.value.length; ++ i) {

                    if(feature.value[i][0] === '/')
                        break

                    location += feature.value[i]
                }

                var f = {
                    key: feature.name,
                    location: parseLocation(location)
                };

                var qualifier;

                /* TODO look for/process specific qualifiers?
                 */
                for(; i < feature.value.length; ++ i) {

                    var qualifierLine = feature.value[i];

                    if(qualifierLine[0] === '/') {

                        qualifier = qualifierLine.split('=')[0];
 
                        var value = qualifierLine.split('=')[1][0] === '"' ? qualifierLine.split('"')[1] : qualifierLine.split('=')[1];

                        if(!f[qualifier])
                            f[qualifier] = [ value ]
                        else
                            f[qualifier].push(value)

                    } else {

                        var value = qualifierLine.split('"')[0];

                        if(qualifier !== '/translation')
                            value = ' ' + value

                        f[qualifier][f[qualifier].length - 1] += value
                    }

                }

                record.features.push(f);
            });

            break;
        };
    });

    if(record.references){

        record.references = record.references.sort(function(a, b) {
            return a.number - b.number;
        });
    }
	
    return record;
}


function parseLocation(location) {

    location = location.trim()

    var match = location.match(/([a-z]+)\((.*)\)/)

    if(match !== null) {

        var modifier = match[1]

        if(modifier === 'complement') {

            var innerLocation = parseLocation(match[2])

            innerLocation.strand = 'complementary'

            return innerLocation

        } else if(modifier === 'join') {

            return match[2].split(',').map(parseLocation)

        } else {

            throw new Error('unknown modifier: ' + modifier)

        }

    } else {

        var partial3Prime = location.indexOf('<') !== -1;
        var partial5Prime = location.indexOf('>') !== -1;

        var startEndMatch = location.replace(/[<>]/g, '').match(/^([0-9]+)\.\.([0-9]+)$/);

        if ( startEndMatch == null && location.match(/([0-9]+)/) ){
            return {
                start: parseInt(location),
                end: parseInt(location),
                partial3Prime: partial3Prime,
                partial5Prime: partial5Prime
            }
        } else {
            return {
                start: parseInt(startEndMatch[1]),
                end: parseInt(startEndMatch[2]),
                partial3Prime: partial3Prime,
                partial5Prime: partial5Prime
            }
        }
    }
}

function parseFlatFile(lines) {

    function getIndent(line) {

        for(var indent = 0; line[indent] == ' '; )
            ++ indent;

        return indent;
    }

    function readFields(indent) {

        var fields = [],
            field,
            valueColumn;

        while(lines.length > 0) {

            var line = lines[0];

            var lineIndent = getIndent(line);

            if(lineIndent < indent)
                break;

            if(lineIndent > indent) {

                if(lineIndent != valueColumn) {

                    /* children of prev field
                     */
                    field.children = readFields(lineIndent);
                    continue;
                }

                /* continuation
                 */
                field.value.push(line.slice(lineIndent));
            }

            if(lineIndent == indent) {

                /* new field
                 */
                var delim = line.indexOf(' ', lineIndent);

                valueColumn = delim + getIndent(line.slice(delim));

                field = {
                    name: line.slice(lineIndent, delim),
                    value: [ line.slice(valueColumn) ]
                };

                fields.push(field);
            }

            lines = lines.slice(1);
        }

        return fields;
    }

    return readFields(0);
}

exports.translationTable = function translationTable(code) {
  //source: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?chapter=cgencodes#SG1
  switch (code) {
    case 2:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile", start: true },
        atc: { letter: "I", symbol: "Ile", start: true },
        ata: { letter: "M", symbol: "Met", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "*", symbol: "*" },
        agg: { letter: "*", symbol: "*" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 3:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "T", symbol: "Thr" },
        ctc: { letter: "T", symbol: "Thr" },
        cta: { letter: "T", symbol: "Thr" },
        ctg: { letter: "T", symbol: "Thr" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "M", symbol: "Met", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 4:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu", start: true },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile", start: true },
        atc: { letter: "I", symbol: "Ile", start: true },
        ata: { letter: "I", symbol: "Ile", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 5:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile", start: true },
        atc: { letter: "I", symbol: "Ile", start: true },
        ata: { letter: "M", symbol: "Met", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "S", symbol: "Ser" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 6:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "Q", symbol: "Gln" },
        tag: { letter: "Q", symbol: "Gln" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 9:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "N", symbol: "Asn" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "S", symbol: "Ser" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 10:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "C", symbol: "Cys" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 11:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile", start: true },
        atc: { letter: "I", symbol: "Ile", start: true },
        ata: { letter: "I", symbol: "Ile", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 12:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "S", symbol: "Ser", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 13:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "M", symbol: "Met", start: true },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "G", symbol: "Gly" },
        agg: { letter: "G", symbol: "Gly" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 14:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "Y", symbol: "Tyr" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "N", symbol: "Asn" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "S", symbol: "Ser" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 15:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "Q", symbol: "Gln" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 16:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "L", symbol: "Leu" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 21:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "M", symbol: "Met" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "N", symbol: "Asn" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "S", symbol: "Ser" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 22:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "*", symbol: "*" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "L", symbol: "Leu" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 23:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "*", symbol: "*" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile", start: true },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 24:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "K", symbol: "Lys" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 25:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "G", symbol: "Gly" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 26:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "A", symbol: "Ala", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 27:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "Q", symbol: "Gln" },
        tag: { letter: "Q", symbol: "Gln" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 28:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 29:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "Y", symbol: "Tyr" },
        tag: { letter: "Y", symbol: "Tyr" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 30:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "E", symbol: "Glu" },
        tag: { letter: "E", symbol: "Glu" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 31:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu" },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu" },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 33:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "Y", symbol: "Tyr" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "W", symbol: "Trp" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "S", symbol: "Ser" },
        agg: { letter: "K", symbol: "Lys" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val", start: true },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
    case 1:
    default:
      return {
        ttt: { letter: "F", symbol: "Phe" },
        ttc: { letter: "F", symbol: "Phe" },
        tta: { letter: "L", symbol: "Leu" },
        ttg: { letter: "L", symbol: "Leu", start: true },
        tct: { letter: "S", symbol: "Ser" },
        tcc: { letter: "S", symbol: "Ser" },
        tca: { letter: "S", symbol: "Ser" },
        tcg: { letter: "S", symbol: "Ser" },
        tat: { letter: "Y", symbol: "Tyr" },
        tac: { letter: "Y", symbol: "Tyr" },
        taa: { letter: "*", symbol: "*" },
        tag: { letter: "*", symbol: "*" },
        tgt: { letter: "C", symbol: "Cys" },
        tgc: { letter: "C", symbol: "Cys" },
        tga: { letter: "*", symbol: "*" },
        tgg: { letter: "W", symbol: "Trp" },
        ctt: { letter: "L", symbol: "Leu" },
        ctc: { letter: "L", symbol: "Leu" },
        cta: { letter: "L", symbol: "Leu" },
        ctg: { letter: "L", symbol: "Leu", start: true },
        cct: { letter: "P", symbol: "Pro" },
        ccc: { letter: "P", symbol: "Pro" },
        cca: { letter: "P", symbol: "Pro" },
        ccg: { letter: "P", symbol: "Pro" },
        cat: { letter: "H", symbol: "His" },
        cac: { letter: "H", symbol: "His" },
        caa: { letter: "Q", symbol: "Gln" },
        cag: { letter: "Q", symbol: "Gln" },
        cgt: { letter: "R", symbol: "Arg" },
        cgc: { letter: "R", symbol: "Arg" },
        cga: { letter: "R", symbol: "Arg" },
        cgg: { letter: "R", symbol: "Arg" },
        att: { letter: "I", symbol: "Ile" },
        atc: { letter: "I", symbol: "Ile" },
        ata: { letter: "I", symbol: "Ile" },
        atg: { letter: "M", symbol: "Met", start: true },
        act: { letter: "T", symbol: "Thr" },
        acc: { letter: "T", symbol: "Thr" },
        aca: { letter: "T", symbol: "Thr" },
        acg: { letter: "T", symbol: "Thr" },
        aat: { letter: "N", symbol: "Asn" },
        aac: { letter: "N", symbol: "Asn" },
        aaa: { letter: "K", symbol: "Lys" },
        aag: { letter: "K", symbol: "Lys" },
        agt: { letter: "S", symbol: "Ser" },
        agc: { letter: "S", symbol: "Ser" },
        aga: { letter: "R", symbol: "Arg" },
        agg: { letter: "R", symbol: "Arg" },
        gtt: { letter: "V", symbol: "Val" },
        gtc: { letter: "V", symbol: "Val" },
        gta: { letter: "V", symbol: "Val" },
        gtg: { letter: "V", symbol: "Val" },
        gct: { letter: "A", symbol: "Ala" },
        gcc: { letter: "A", symbol: "Ala" },
        gca: { letter: "A", symbol: "Ala" },
        gcg: { letter: "A", symbol: "Ala" },
        gat: { letter: "D", symbol: "Asp" },
        gac: { letter: "D", symbol: "Asp" },
        gaa: { letter: "E", symbol: "Glu" },
        gag: { letter: "E", symbol: "Glu" },
        ggt: { letter: "G", symbol: "Gly" },
        ggc: { letter: "G", symbol: "Gly" },
        gga: { letter: "G", symbol: "Gly" },
        ggg: { letter: "G", symbol: "Gly" },
      };
  }
}